spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hangman
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com:
      nielsen:
        hangman: ${LOG_LEVEL:DEBUG}
    org:
      springframework: ${LOG_LEVEL:INFO}
